name: mamasafe
description: AI-powered maternal mortality risk prediction for CHWs in Cameroon
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.7.0
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.5
  path: ^1.9.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.1
  intl: ^0.20.2
  shared_preferences: ^2.3.4
  fl_chart: ^0.70.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  webview_flutter: ^4.10.0
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.13
  drift_dev: ^2.22.1
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/l10n/
    - assets/images/logo.svg
